//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MensajeriaEntities : DbContext
    {
        public MensajeriaEntities()
            : base("name=MensajeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conversacion> Conversacions { get; set; }
        public virtual DbSet<Envio> Envios { get; set; }
        public virtual DbSet<Mensaje> Mensajes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int AddUsusario(string nombre, string apellidoPaterno, string apellidoMaterno, string email, string password)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("ApellidoPaterno", apellidoPaterno) :
                new ObjectParameter("ApellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("ApellidoMaterno", apellidoMaterno) :
                new ObjectParameter("ApellidoMaterno", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddUsusario", nombreParameter, apellidoPaternoParameter, apellidoMaternoParameter, emailParameter, passwordParameter);
        }
    
        public virtual ObjectResult<GetEmail_Result> GetEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetEmail_Result>("GetEmail", emailParameter);
        }
    
        public virtual ObjectResult<GetByIdConversacionUsuario_Result> GetByIdConversacionUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdConversacionUsuario_Result>("GetByIdConversacionUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<BusquedaUsuario_Result> BusquedaUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BusquedaUsuario_Result>("BusquedaUsuario", usuarioParameter);
        }
    
        public virtual int AddConversacion(Nullable<int> idReceptor, Nullable<int> idEmisor)
        {
            var idReceptorParameter = idReceptor.HasValue ?
                new ObjectParameter("IdReceptor", idReceptor) :
                new ObjectParameter("IdReceptor", typeof(int));
    
            var idEmisorParameter = idEmisor.HasValue ?
                new ObjectParameter("IdEmisor", idEmisor) :
                new ObjectParameter("IdEmisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddConversacion", idReceptorParameter, idEmisorParameter);
        }
    
        public virtual int AddMensaje(string mensaje, Nullable<int> ultimoMensaje, Nullable<int> idEmisor, Nullable<int> idReceptor, Nullable<int> idConversacion)
        {
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            var ultimoMensajeParameter = ultimoMensaje.HasValue ?
                new ObjectParameter("UltimoMensaje", ultimoMensaje) :
                new ObjectParameter("UltimoMensaje", typeof(int));
    
            var idEmisorParameter = idEmisor.HasValue ?
                new ObjectParameter("IdEmisor", idEmisor) :
                new ObjectParameter("IdEmisor", typeof(int));
    
            var idReceptorParameter = idReceptor.HasValue ?
                new ObjectParameter("IdReceptor", idReceptor) :
                new ObjectParameter("IdReceptor", typeof(int));
    
            var idConversacionParameter = idConversacion.HasValue ?
                new ObjectParameter("IdConversacion", idConversacion) :
                new ObjectParameter("IdConversacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddMensaje", mensajeParameter, ultimoMensajeParameter, idEmisorParameter, idReceptorParameter, idConversacionParameter);
        }
    
        public virtual ObjectResult<GetByIdConversacioEnvios_Result> GetByIdConversacioEnvios(Nullable<int> idConversacion)
        {
            var idConversacionParameter = idConversacion.HasValue ?
                new ObjectParameter("IdConversacion", idConversacion) :
                new ObjectParameter("IdConversacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetByIdConversacioEnvios_Result>("GetByIdConversacioEnvios", idConversacionParameter);
        }
    }
}
